; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/Users/jocrau/Documents/typoplanet/workspaces/eclipse/clj-rdfa/src/clj/rdfa/dom.clj

(ns rdfa.dom)


(defprotocol DomAccess
  (get-name [this])
  (get-attr [this attr-name])
  (get-ns-map [this])
  (is-root? [this])
  (find-by-tag [this tag])
  (get-child-elements [this])
  (get-text [this])
  (get-inner-xml [this xmlns-map lang]))

